# Database config
database: mastoBot.db # Path to the SQLite database

# Mastodon.py settings
api:
    timeout: 10 # API timeout

# Behaviour to favourite posts
favourites:
    parents_only: false # Must be parent
    followers_only: true # Must be follower
    alt_text_required: true # Must contain alt-text if media is present

# Behaviour to boost posts
boosts:
    parents_only: true # Must be parent
    followers_only: true # Must be follower
    alt_text_required: true # Must contain alt-text if media is present