redis:
    port: 6379
    host: host.docker.internal
api:
    timeout: 10
favourites:
    parents_only: false
    followers_only: true
    alt_text_required: true
boosts:
    parents_only: true
    followers_only: true
    alt_text_required: true
alt_text_required:
    missing_message:
        enabled: true
        file: 'missing_alt_text.txt'