version: "3.3"

services:
  mastobot-worker:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command: ["python3", "main.py"]
    networks:
      - mastobot-network

  mastobot-redis:
    image: "redis/redis-stack"
    volumes:
      - mastobot-redis-data:/data
    networks:
      - mastobot-network
    ports:
      - "${REDIS_PORT}:6379"
      - "${REDIS_INSIGHT_PORT}:8001"

networks:
  mastobot-network:
