[build-system]
requires = ["setuptools>=58.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "MastoBot.py"
version = "0.0.1"
description = "A generic implementation to easily create and implement bots for Mastodon"
keywords = ["mastodon", "api", "bot"]
authors = [
  { name = "Erik Dreyer", email = "erik.dreyer@protonmail.com" }
]
license = { text = "GPL-3.0" }
readme = "README.md"
requires-python = ">=3.12"
classifiers = [
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    'Intended Audience :: Developers',
    'Topic :: Communications',
    'Programming Language :: Python :: 3',
]
dependencies = [
  "Mastodon.py",
  "Jinja2",
  "PyYAML"
]

[tool.setuptools.packages.find]
where = ["."]  # list of folders that contain the packages (["."] by default)
include = ["mastoBot*"]  # package names should match these glob patterns (["*"] by default)

[project.urls]
"Homepage" = "https://github.com/e-dreyer/MastoBot"
"Bug Tracker" = "https://github.com/e-dreyer/MastoBot/issues"
"Pull Requests" = "https://github.com/e-dreyer/MastoBot/pulls"
"Wiki" = "https://github.com/e-dreyer/MastoBot/wiki"