version: "3.3"

services:
  mastobot-worker:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command: ["python3", "main.py"]
    networks:
      - mastobot-network



networks:
  mastobot-network:
